version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[composer] "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: [ "*" ]
    commit-message:
      prefix: "[actions] "
